dist: trusty

language: node_js
node_js:
- "9"

cache: yarn

env:
  - CHROME_BIN=/usr/bin/google-chrome

matrix:
  include:
  - env: TO_TEST=leveldb
  - env: TO_TEST=lmdb
  - env: TO_TEST=ESLint
#  - os: osx
#    env: TO_TEST=Karma/Travis_CI/Safari
#    osx_image: xcode8.3
  - env: TO_TEST=Karma/SauceLabs/Edge_15
    addons:
      sauce_connect:
        username: nimiq
      jwt:
        secure: UIsO/eO8sTJSAKcKIEej74QCa9cS3zPd0dmnJs6K9K8PcA55eDbOSPgKLxzhFHjyd/+MEjNssmuJTzZ5Wu3ma79z28muALrS65LjBRLJzP1eYGUc/mBHD998S97yllvJOO3vemf8Rb9GxaJCBdDbY5aJlNuJNT74XUzppsWZ2Og3yQaFUtVzfQrVbFRA12Qwm7tgM75q+kpVe+RAn7iIqrPjKTwSTdkd5AkHvSA87S8SadpGr5WKA+M/yuDomsO+58AuKG7lHq3Y9sO7N372OyFEnktp+jvEbHDlk8iJF7s/xB9YvRZYEZyY0MF6E350zXN50hKEgguR9TVXiSsWZnKeHA+lWUz45/jec0k0SrSaBSkQxBc5quNPZZeUzVd++n3IFVh1lc+YxxSLadIdfwjlJbaDdR8+yPpAx/7Q0UDb65XVD5ar7a2gqrJgxtZaa5TOLo1AHoWkkdBzHWL9wYO4cfGvneIGeEgXjMYSCBUBHGoBnQGTjTREMer2pLo5HB/HzDKRq5SRftQYTCavEzAau5/ZqC26k5h2X/55JijE/6FKeoqEYS12fCT+be7EyEVjX6iQIeV77Bc+OVvlF2Fep0omZKeb9HSP3djURrjxwOGokBOxhXtdHvbKPizAqLYh2x9uEz/Ed6upVsa8q9ByrB6GCsYpU05Q6QuWzBA=
#  - env: TO_TEST=Karma/SauceLabs/Safari_11
#    addons:
#      sauce_connect:
#        username: nimiq
#      jwt:
#        secure: UIsO/eO8sTJSAKcKIEej74QCa9cS3zPd0dmnJs6K9K8PcA55eDbOSPgKLxzhFHjyd/+MEjNssmuJTzZ5Wu3ma79z28muALrS65LjBRLJzP1eYGUc/mBHD998S97yllvJOO3vemf8Rb9GxaJCBdDbY5aJlNuJNT74XUzppsWZ2Og3yQaFUtVzfQrVbFRA12Qwm7tgM75q+kpVe+RAn7iIqrPjKTwSTdkd5AkHvSA87S8SadpGr5WKA+M/yuDomsO+58AuKG7lHq3Y9sO7N372OyFEnktp+jvEbHDlk8iJF7s/xB9YvRZYEZyY0MF6E350zXN50hKEgguR9TVXiSsWZnKeHA+lWUz45/jec0k0SrSaBSkQxBc5quNPZZeUzVd++n3IFVh1lc+YxxSLadIdfwjlJbaDdR8+yPpAx/7Q0UDb65XVD5ar7a2gqrJgxtZaa5TOLo1AHoWkkdBzHWL9wYO4cfGvneIGeEgXjMYSCBUBHGoBnQGTjTREMer2pLo5HB/HzDKRq5SRftQYTCavEzAau5/ZqC26k5h2X/55JijE/6FKeoqEYS12fCT+be7EyEVjX6iQIeV77Bc+OVvlF2Fep0omZKeb9HSP3djURrjxwOGokBOxhXtdHvbKPizAqLYh2x9uEz/Ed6upVsa8q9ByrB6GCsYpU05Q6QuWzBA=
#  - env: TO_TEST=Karma/SauceLabs/Safari_10.1 USE_BABEL=1
#    addons:
#      sauce_connect:
#        username: nimiq
#      jwt:
#        secure: UIsO/eO8sTJSAKcKIEej74QCa9cS3zPd0dmnJs6K9K8PcA55eDbOSPgKLxzhFHjyd/+MEjNssmuJTzZ5Wu3ma79z28muALrS65LjBRLJzP1eYGUc/mBHD998S97yllvJOO3vemf8Rb9GxaJCBdDbY5aJlNuJNT74XUzppsWZ2Og3yQaFUtVzfQrVbFRA12Qwm7tgM75q+kpVe+RAn7iIqrPjKTwSTdkd5AkHvSA87S8SadpGr5WKA+M/yuDomsO+58AuKG7lHq3Y9sO7N372OyFEnktp+jvEbHDlk8iJF7s/xB9YvRZYEZyY0MF6E350zXN50hKEgguR9TVXiSsWZnKeHA+lWUz45/jec0k0SrSaBSkQxBc5quNPZZeUzVd++n3IFVh1lc+YxxSLadIdfwjlJbaDdR8+yPpAx/7Q0UDb65XVD5ar7a2gqrJgxtZaa5TOLo1AHoWkkdBzHWL9wYO4cfGvneIGeEgXjMYSCBUBHGoBnQGTjTREMer2pLo5HB/HzDKRq5SRftQYTCavEzAau5/ZqC26k5h2X/55JijE/6FKeoqEYS12fCT+be7EyEVjX6iQIeV77Bc+OVvlF2Fep0omZKeb9HSP3djURrjxwOGokBOxhXtdHvbKPizAqLYh2x9uEz/Ed6upVsa8q9ByrB6GCsYpU05Q6QuWzBA=
  - env: TO_TEST=Karma/Travis_CI/Chrome_Stable
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
  - env: TO_TEST=Karma/Travis_CI/Chrome_Stable USE_BABEL=1
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
  - env: TO_TEST=Karma/Travis_CI/Chrome_Beta
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-beta
#  - env: TO_TEST=Karma/SauceLabs/Chrome_Old
#    addons:
#      sauce_connect:
#        username: nimiq
#      jwt:
#        secure: UIsO/eO8sTJSAKcKIEej74QCa9cS3zPd0dmnJs6K9K8PcA55eDbOSPgKLxzhFHjyd/+MEjNssmuJTzZ5Wu3ma79z28muALrS65LjBRLJzP1eYGUc/mBHD998S97yllvJOO3vemf8Rb9GxaJCBdDbY5aJlNuJNT74XUzppsWZ2Og3yQaFUtVzfQrVbFRA12Qwm7tgM75q+kpVe+RAn7iIqrPjKTwSTdkd5AkHvSA87S8SadpGr5WKA+M/yuDomsO+58AuKG7lHq3Y9sO7N372OyFEnktp+jvEbHDlk8iJF7s/xB9YvRZYEZyY0MF6E350zXN50hKEgguR9TVXiSsWZnKeHA+lWUz45/jec0k0SrSaBSkQxBc5quNPZZeUzVd++n3IFVh1lc+YxxSLadIdfwjlJbaDdR8+yPpAx/7Q0UDb65XVD5ar7a2gqrJgxtZaa5TOLo1AHoWkkdBzHWL9wYO4cfGvneIGeEgXjMYSCBUBHGoBnQGTjTREMer2pLo5HB/HzDKRq5SRftQYTCavEzAau5/ZqC26k5h2X/55JijE/6FKeoqEYS12fCT+be7EyEVjX6iQIeV77Bc+OVvlF2Fep0omZKeb9HSP3djURrjxwOGokBOxhXtdHvbKPizAqLYh2x9uEz/Ed6upVsa8q9ByrB6GCsYpU05Q6QuWzBA=
  - env: TO_TEST=Karma/Travis_CI/Firefox_Stable
    addons:
      firefox: latest
  - env: TO_TEST=Karma/Travis_CI/Firefox_ESR
    addons:
      firefox: latest-esr
  - env: TO_TEST=Karma/Travis_CI/Firefox_Beta
    addons:
      firefox: latest-beta
#  - env: TO_TEST=Karma/Travis_CI/Firefox_56
#    addons:
#      firefox: 56
#  - env: TO_TEST=Karma/Travis_CI/Firefox_55
#    addons:
#      firefox: 55

before_install:
- if [[ "$TO_TEST" == Karma/Travis_CI/Firefox_* ]] || [[ "$TO_TEST" == Karma/Travis_CI/Chrome_* ]]; then export DISPLAY=:99.0; fi
- if [[ "$TO_TEST" == Karma/Travis_CI/Firefox_* ]] || [[ "$TO_TEST" == Karma/Travis_CI/Chrome_* ]]; then sh -e /etc/init.d/xvfb start; fi
- npm install -g gulp

before_script:
- node_modules/.bin/gulp build
- node_modules/.bin/gulp build-leveldb build-leveldb-istanbul

script:
- if [[ "$TO_TEST" == Karma/SauceLabs/Chrome_Old ]]; then export KARMA_BROWSERS="SL_Chrome_61,SL_Chrome_60,SL_Chrome_59,SL_Chrome_58" TO_TEST=Karma; fi
- if [[ "$TO_TEST" == Karma/SauceLabs/* ]]; then export KARMA_BROWSERS="SL_$(basename "$TO_TEST")" TO_TEST=Karma; fi
- if [[ "$TO_TEST" == Karma/Travis_CI/Chrome_* ]] && [ "$KARMA_BROWSERS" = "" ]; then export KARMA_BROWSERS=Travis_Chrome TO_TEST=Karma USE_ISTANBUL=1; fi
- if [[ "$TO_TEST" == Karma/Travis_CI/Firefox_* ]] && [ "$KARMA_BROWSERS" = "" ]; then export KARMA_BROWSERS=Firefox TO_TEST=Karma USE_ISTANBUL=1; fi
- if [[ "$TO_TEST" == Karma/Travis_CI/* ]] && [ "$KARMA_BROWSERS" = "" ]; then export KARMA_BROWSERS=Safari TO_TEST=Karma; fi
- if [ "$TO_TEST" = "Karma" ]; then node_modules/.bin/karma start; fi
- if [ "$TO_TEST" = "leveldb" ]; then node_modules/.bin/jasmine --config=spec/support/leveldb-jasmine.json; fi
- if [ "$TO_TEST" = "lmdb" ]; then node_modules/.bin/jasmine; fi
- if [ "$TO_TEST" = "ESLint" ]; then node_modules/.bin/eslint src/main src/test *.js && node_modules/.bin/esdoc; fi
- if [ "$USE_ISTANBUL" = "1" ]; then node_modules/.bin/codecov; fi
